export {
    DOC_H,
    DOC_W,
    isDark,
    resolvePaletteByTemplate,
    resolveSlideRole,
    sanitizeImageElements,
    textOn,
    truncateText,
    withAlpha,
    type CarouselElement,
    type ResolvedPalette,
    type SlideCopy,
    type SlideRole,
    type TemplateBuildParams,
} from "../../../../shared/templateEngine";
