import type { Carousel } from "./types";

const carousel: Carousel = {
    meta: {
        theme: "eleganteModerno2025",
        title: "Principais motivos para ter um contador",
    },
    slides: [
        {
            id: "s1",
            layers: {
                background: [
                    {
                        type: "background",
                        x: 0,
                        y: 0,
                        width: 1080,
                        height: 1350,
                        fill: "#F6F3EE",
                    },
                    {
                        type: "gradientRect",
                        x: 0,
                        y: 0,
                        width: 1080,
                        height: 1350,
                        kind: "linear",
                        start: { x: 0, y: 0 },
                        end: { x: 1080, y: 1350 },
                        stops: [
                            [0, "rgba(255,255,255,0.75)"],
                            [1, "rgba(226,216,201,0.28)"],
                        ],
                        opacity: 1,
                    },
                ],
                atmosphere: [
                    {
                        type: "glow",
                        x: 160,
                        y: 180,
                        r: 220,
                        color: "#D8C3A5",
                        blur: 120,
                        opacity: 0.24,
                    },
                    {
                        type: "glow",
                        x: 900,
                        y: 260,
                        r: 180,
                        color: "#B7C9C0",
                        blur: 120,
                        opacity: 0.18,
                    },
                    {
                        type: "path",
                        x: 760,
                        y: 110,
                        data: "M0 90 C60 0, 160 0, 220 90 C160 180, 60 180, 0 90 Z",
                        fill: "rgba(36,45,44,0.06)",
                        opacity: 1,
                    },
                    {
                        type: "glassCard",
                        x: 85,
                        y: 860,
                        width: 910,
                        height: 320,
                        radius: 36,
                        fill: "rgba(255,255,255,0.42)",
                        stroke: "rgba(36,45,44,0.08)",
                        strokeWidth: 1.2,
                        opacity: 1,
                        shadow: { blur: 32, y: 14, opacity: 0.12 },
                    },
                ],
                content: [
                    {
                        type: "text",
                        x: 88,
                        y: 110,
                        text: "EMPREENDEDORISMO • FINANÇAS • GESTÃO",
                        fill: "#6D675E",
                        fontSize: 28,
                        fontFamily: "Inter",
                        fontStyle: "600",
                        letterSpacing: 2,
                        opacity: 0.95,
                    },
                    {
                        type: "text",
                        x: 86,
                        y: 250,
                        width: 760,
                        text: "Principais motivos para ter um contador",
                        fill: "#1F2523",
                        fontSize: 78,
                        fontFamily: "Georgia",
                        fontStyle: "bold",
                        lineHeight: 1.05,
                    },
                    {
                        type: "text",
                        x: 92,
                        y: 906,
                        width: 860,
                        text: "Um bom contador não serve só para “mexer com imposto”. Ele ajuda a proteger sua empresa, reduzir erros e melhorar decisões financeiras.",
                        fill: "#2F3734",
                        fontSize: 38,
                        fontFamily: "Inter",
                        lineHeight: 1.35,
                    },
                ],
                ui: [
                    {
                        type: "text",
                        x: 91,
                        y: 1240,
                        text: "Arraste para o lado",
                        fill: "#7A746B",
                        fontSize: 24,
                        fontFamily: "Inter",
                        fontStyle: "500",
                        letterSpacing: 1,
                    },
                    {
                        type: "text",
                        x: 955,
                        y: 1236,
                        text: "01",
                        fill: "#1F2523",
                        fontSize: 28,
                        fontFamily: "Inter",
                        fontStyle: "700",
                    },
                ],
            },
        },
        {
            id: "s2",
            layers: {
                background: [
                    {
                        type: "background",
                        x: 0,
                        y: 0,
                        width: 1080,
                        height: 1350,
                        fill: "#FBF9F6",
                    },
                ],
                atmosphere: [
                    {
                        type: "gradientRect",
                        x: 0,
                        y: 0,
                        width: 1080,
                        height: 480,
                        kind: "linear",
                        start: { x: 0, y: 0 },
                        end: { x: 1080, y: 0 },
                        stops: [
                            [0, "rgba(213,188,153,0.22)"],
                            [1, "rgba(213,188,153,0.04)"],
                        ],
                        opacity: 1,
                    },
                    {
                        type: "glassCard",
                        x: 70,
                        y: 320,
                        width: 940,
                        height: 790,
                        radius: 34,
                        fill: "rgba(255,255,255,0.62)",
                        stroke: "rgba(31,37,35,0.08)",
                        strokeWidth: 1,
                        shadow: { blur: 24, y: 12, opacity: 0.08 },
                    },
                    {
                        type: "path",
                        x: 850,
                        y: 180,
                        data: "M0 60 C40 0, 120 0, 160 60 C120 120, 40 120, 0 60 Z",
                        fill: "rgba(31,37,35,0.05)",
                    },
                ],
                content: [
                    {
                        type: "text",
                        x: 88,
                        y: 92,
                        text: "1. Evitar problemas com impostos",
                        fill: "#1E2422",
                        fontSize: 62,
                        fontFamily: "Georgia",
                        fontStyle: "bold",
                        width: 820,
                        lineHeight: 1.1,
                    },
                    {
                        type: "text",
                        x: 110,
                        y: 390,
                        width: 820,
                        text: "Tributos pagos errados, atrasos e declarações inconsistentes podem gerar multas e dor de cabeça. O contador ajuda a manter tudo em conformidade.",
                        fill: "#33403C",
                        fontSize: 40,
                        fontFamily: "Inter",
                        lineHeight: 1.42,
                    },
                    {
                        type: "text",
                        x: 110,
                        y: 720,
                        width: 820,
                        text: "• organiza prazos\n• reduz riscos fiscais\n• evita erros em declarações",
                        fill: "#1F2523",
                        fontSize: 36,
                        fontFamily: "Inter",
                        lineHeight: 1.7,
                    },
                ],
                ui: [
                    {
                        type: "text",
                        x: 92,
                        y: 1238,
                        text: "Segurança fiscal",
                        fill: "#7C756A",
                        fontSize: 24,
                        fontFamily: "Inter",
                        fontStyle: "500",
                        letterSpacing: 0.5,
                    },
                    {
                        type: "text",
                        x: 953,
                        y: 1236,
                        text: "02",
                        fill: "#1F2523",
                        fontSize: 28,
                        fontFamily: "Inter",
                        fontStyle: "700",
                    },
                ],
            },
        },
        {
            id: "s3",
            layers: {
                background: [
                    {
                        type: "background",
                        x: 0,
                        y: 0,
                        width: 1080,
                        height: 1350,
                        fill: "#F5F2EC",
                    },
                ],
                atmosphere: [
                    {
                        type: "glow",
                        x: 880,
                        y: 210,
                        r: 240,
                        color: "#C2B09A",
                        blur: 130,
                        opacity: 0.24,
                    },
                    {
                        type: "glassCard",
                        x: 70,
                        y: 250,
                        width: 940,
                        height: 860,
                        radius: 34,
                        fill: "rgba(255,255,255,0.50)",
                        stroke: "rgba(31,37,35,0.08)",
                        strokeWidth: 1,
                        shadow: { blur: 30, y: 14, opacity: 0.1 },
                    },
                ],
                content: [
                    {
                        type: "text",
                        x: 86,
                        y: 92,
                        text: "2. Pagar menos imposto de forma legal",
                        fill: "#1D2421",
                        fontSize: 60,
                        fontFamily: "Georgia",
                        fontStyle: "bold",
                        width: 860,
                        lineHeight: 1.1,
                    },
                    {
                        type: "text",
                        x: 110,
                        y: 345,
                        width: 830,
                        text: "Muitas empresas pagam mais do que deveriam por escolher o regime tributário errado ou por não aproveitar enquadramentos possíveis.",
                        fill: "#33403C",
                        fontSize: 39,
                        fontFamily: "Inter",
                        lineHeight: 1.42,
                    },
                    {
                        type: "text",
                        x: 110,
                        y: 700,
                        width: 820,
                        text: "Com análise contábil, fica mais fácil entender se o melhor caminho é Simples Nacional, Lucro Presumido ou outro enquadramento compatível com o negócio.",
                        fill: "#1F2523",
                        fontSize: 35,
                        fontFamily: "Inter",
                        lineHeight: 1.55,
                    },
                ],
                ui: [
                    {
                        type: "text",
                        x: 92,
                        y: 1238,
                        text: "Economia inteligente",
                        fill: "#7C756A",
                        fontSize: 24,
                        fontFamily: "Inter",
                        fontStyle: "500",
                    },
                    {
                        type: "text",
                        x: 953,
                        y: 1236,
                        text: "03",
                        fill: "#1F2523",
                        fontSize: 28,
                        fontFamily: "Inter",
                        fontStyle: "700",
                    },
                ],
            },
        },
        {
            id: "s4",
            layers: {
                background: [
                    {
                        type: "background",
                        x: 0,
                        y: 0,
                        width: 1080,
                        height: 1350,
                        fill: "#FCFAF7",
                    },
                ],
                atmosphere: [
                    {
                        type: "gradientRect",
                        x: 0,
                        y: 0,
                        width: 1080,
                        height: 1350,
                        kind: "linear",
                        start: { x: 0, y: 0 },
                        end: { x: 0, y: 1350 },
                        stops: [
                            [0, "rgba(183,201,192,0.18)"],
                            [1, "rgba(255,255,255,0)"],
                        ],
                        opacity: 1,
                    },
                    {
                        type: "glassCard",
                        x: 70,
                        y: 300,
                        width: 940,
                        height: 760,
                        radius: 34,
                        fill: "rgba(255,255,255,0.58)",
                        stroke: "rgba(31,37,35,0.08)",
                        strokeWidth: 1,
                        shadow: { blur: 26, y: 12, opacity: 0.08 },
                    },
                    {
                        type: "path",
                        x: 120,
                        y: 200,
                        data: "M60 0 C93 0 120 27 120 60 C120 93 93 120 60 120 C27 120 0 93 0 60 C0 27 27 0 60 0 Z",
                        fill: "rgba(31,37,35,0.05)",
                    },
                ],
                content: [
                    {
                        type: "text",
                        x: 86,
                        y: 92,
                        text: "3. Organizar melhor a saúde financeira da empresa",
                        fill: "#1D2421",
                        fontSize: 57,
                        fontFamily: "Georgia",
                        fontStyle: "bold",
                        width: 900,
                        lineHeight: 1.12,
                    },
                    {
                        type: "text",
                        x: 108,
                        y: 390,
                        width: 835,
                        text: "Ter contador também significa enxergar com mais clareza faturamento, despesas, lucro e fluxo de caixa.",
                        fill: "#34403C",
                        fontSize: 40,
                        fontFamily: "Inter",
                        lineHeight: 1.42,
                    },
                    {
                        type: "text",
                        x: 108,
                        y: 685,
                        width: 830,
                        text: "Sem números organizados, o empreendedor decide no escuro. Com acompanhamento contábil, fica mais fácil crescer com base em dados reais.",
                        fill: "#1F2523",
                        fontSize: 35,
                        fontFamily: "Inter",
                        lineHeight: 1.56,
                    },
                ],
                ui: [
                    {
                        type: "text",
                        x: 92,
                        y: 1238,
                        text: "Mais clareza para decidir",
                        fill: "#7C756A",
                        fontSize: 24,
                        fontFamily: "Inter",
                        fontStyle: "500",
                    },
                    {
                        type: "text",
                        x: 953,
                        y: 1236,
                        text: "04",
                        fill: "#1F2523",
                        fontSize: 28,
                        fontFamily: "Inter",
                        fontStyle: "700",
                    },
                ],
            },
        },
        {
            id: "s5",
            layers: {
                background: [
                    {
                        type: "background",
                        x: 0,
                        y: 0,
                        width: 1080,
                        height: 1350,
                        fill: "#F7F4EF",
                    },
                ],
                atmosphere: [
                    {
                        type: "glow",
                        x: 250,
                        y: 180,
                        r: 200,
                        color: "#B7C9C0",
                        blur: 120,
                        opacity: 0.22,
                    },
                    {
                        type: "glassCard",
                        x: 70,
                        y: 280,
                        width: 940,
                        height: 800,
                        radius: 34,
                        fill: "rgba(255,255,255,0.56)",
                        stroke: "rgba(31,37,35,0.08)",
                        strokeWidth: 1,
                        shadow: { blur: 28, y: 12, opacity: 0.09 },
                    },
                ],
                content: [
                    {
                        type: "text",
                        x: 86,
                        y: 92,
                        text: "4. Ganhar apoio em momentos importantes",
                        fill: "#1D2421",
                        fontSize: 60,
                        fontFamily: "Georgia",
                        fontStyle: "bold",
                        width: 860,
                        lineHeight: 1.1,
                    },
                    {
                        type: "text",
                        x: 108,
                        y: 385,
                        width: 830,
                        text: "Abrir empresa, contratar funcionário, emitir pró-labore, buscar crédito ou se preparar para crescer: tudo isso fica mais simples com orientação contábil.",
                        fill: "#34403C",
                        fontSize: 38,
                        fontFamily: "Inter",
                        lineHeight: 1.45,
                    },
                    {
                        type: "text",
                        x: 108,
                        y: 760,
                        width: 820,
                        text: "O contador ajuda a tomar decisões com mais segurança e menos improviso.",
                        fill: "#1F2523",
                        fontSize: 36,
                        fontFamily: "Inter",
                        lineHeight: 1.5,
                    },
                ],
                ui: [
                    {
                        type: "text",
                        x: 92,
                        y: 1238,
                        text: "Suporte estratégico",
                        fill: "#7C756A",
                        fontSize: 24,
                        fontFamily: "Inter",
                        fontStyle: "500",
                    },
                    {
                        type: "text",
                        x: 953,
                        y: 1236,
                        text: "05",
                        fill: "#1F2523",
                        fontSize: 28,
                        fontFamily: "Inter",
                        fontStyle: "700",
                    },
                ],
            },
        },
        {
            id: "s6",
            layers: {
                background: [
                    {
                        type: "background",
                        x: 0,
                        y: 0,
                        width: 1080,
                        height: 1350,
                        fill: "#1F2523",
                    },
                    {
                        type: "gradientRect",
                        x: 0,
                        y: 0,
                        width: 1080,
                        height: 1350,
                        kind: "linear",
                        start: { x: 0, y: 0 },
                        end: { x: 1080, y: 1350 },
                        stops: [
                            [0, "rgba(255,255,255,0.02)"],
                            [1, "rgba(212,188,155,0.12)"],
                        ],
                        opacity: 1,
                    },
                ],
                atmosphere: [
                    {
                        type: "glow",
                        x: 860,
                        y: 180,
                        r: 260,
                        color: "#D8C3A5",
                        blur: 150,
                        opacity: 0.18,
                    },
                    {
                        type: "glassCard",
                        x: 70,
                        y: 790,
                        width: 940,
                        height: 320,
                        radius: 34,
                        fill: "rgba(255,255,255,0.06)",
                        stroke: "rgba(255,255,255,0.12)",
                        strokeWidth: 1,
                        shadow: { blur: 30, y: 14, opacity: 0.16 },
                    },
                ],
                content: [
                    {
                        type: "text",
                        x: 86,
                        y: 130,
                        text: "No fim, ter um contador é investir em tranquilidade, economia e organização.",
                        fill: "#F4EFE7",
                        fontSize: 68,
                        fontFamily: "Georgia",
                        fontStyle: "bold",
                        width: 900,
                        lineHeight: 1.1,
                    },
                    {
                        type: "text",
                        x: 92,
                        y: 860,
                        width: 840,
                        text: "Se você empreende ou quer formalizar seu negócio, contar com acompanhamento contábil pode evitar prejuízos e abrir caminho para crescer com mais segurança.",
                        fill: "#E9E1D6",
                        fontSize: 37,
                        fontFamily: "Inter",
                        lineHeight: 1.45,
                    },
                    {
                        type: "text",
                        x: 92,
                        y: 1160,
                        width: 820,
                        text: "Salve este post e envie para alguém que precisa organizar melhor a empresa.",
                        fill: "#D8C3A5",
                        fontSize: 31,
                        fontFamily: "Inter",
                        fontStyle: "600",
                        lineHeight: 1.35,
                    },
                ],
                ui: [
                    {
                        type: "text",
                        x: 92,
                        y: 64,
                        text: "Conclusão",
                        fill: "#BFAE98",
                        fontSize: 26,
                        fontFamily: "Inter",
                        fontStyle: "600",
                        letterSpacing: 1.2,
                    },
                    {
                        type: "text",
                        x: 953,
                        y: 1236,
                        text: "06",
                        fill: "#F4EFE7",
                        fontSize: 28,
                        fontFamily: "Inter",
                        fontStyle: "700",
                    },
                ],
            },
        },
    ],
};

export default carousel;